const String KProudectColletion = "Products";
const String KShirtsColletion = "Shirts";
const String KPantsColletion = "Pants";
const String KTshirtsColletion = "Tshirt";
const String KshoseColletion = "Shoes";
const String KWomenColletion = "Woman";

const String KProudectName = "ProductName";
const String KProudectDescription = "ProductDescription";
const String KProudectCatogery = "ProductCatogery";
const String KProudectLoction = "ProductLoction";
const String KProudectLoction2 = "ProductLoction2";
const String KProudectLoction3 = "ProductLoction3";
const String KProudectPrice = "ProductPrice";
const String KProudectPrand = "ProductPrand";
const String KProudectAvSize = "Av size";
const List<String> Show = [];
const String KProudectCondation = "ProductCondation";
const String Kcover = "Cover";
const String KcoverPhoto = "CoverPhoto";
const String KorederDetiles = "OrdarDetils";
const kTotallPrice = 'TotallPrice';
const String Koreder = "Ordar";
const String KQantan = "Ordar";
String LName, add, city, gov, pN;
String FName = "[]";
List<String> addres;
String tast;
const kAddress = 'Address';
bool isLoged;
List AVS = [];
